# basic option
title: Hathaway Digital
author: Mike Hathaway
email: mike@mikehathaway.com
description: Company Website
twitter_username: mikehathaway
github_username: mjh2901

baseurl: "mjh2901/hathawaydigital"
url: "https://hathawaydigital.com"

# build settings
markdown: kramdown

remote_theme: sunbliss/photorama
